task:  # task specific config
  debug: false
  seed: 42
  dirname: train_cropped_images

model:
  arch: "unet"
  backbone: "tu-tf_efficientnetv2_s.in21k_ft_in1k"
  resume_path: null
  ema: false
  ema_decay: 0.999
  ema_update_after_step: 0
  swa: false
  freeze_backbone: false
  freeze_end_epoch: 16
  drop_path_rate: 0.0
  drop_rate: 0.0
  attn_drop_rate: 0.0
  img_size: 128
  img_depth: 16
  in_channels: 3
  d_model: 128
  num_layers: 2
  kernel_size: 5
  use_lstm: false
  use_attn: false
  depth: 50
  pool: "avg"  # avg, gem
  with_pool2: true
  normalize_patch: false
  depth_flip: false
  stride: "pool"  # pool, conv
  class_num: 5
  train_stride: 0.5
  use_intermediate_conv: true

data:
  fold_num: 5
  fold_id: 0
  num_workers: 0
  batch_size: 2
  train_all: false

trainer:
  max_epochs: 32
  devices: "auto"  # list or str, -1 to indicate all available devices
  strategy: "auto"  # ddp
  check_val_every_n_epoch: 1
  sync_batchnorm: false
  accelerator: "cpu"  # cpu, gpu, tpu, ipu, hpu, mps, auto
  precision: 32  # 16, 32, 64, bf16
  gradient_clip_val: null
  accumulate_grad_batches: 1
  deterministic: true

test:
  mode: val  # test or val
  output_dir: preds_results
  tta: false
  target: axial
  dirname: null

opt:
  opt: "AdamW"  # SGD, Adam, AdamW...
  lr: 1e-4
  weight_decay: 0.01

scheduler:
  sched: "cosine"
  min_lr: 0.0
  warmup_epochs: 0

loss:
  name: "mse"  # bce, focal
  alpha: 0.25
  mixup: 0.0
  cutmix: 0.0
  neg_weight: 0.1

wandb:
  project: kaggle-czii
  name: null
  fast_dev_run: false
